### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by jpabeem** [anigenero/react-class-validator#2]
Hey,

First of all, awesome library! Just what we needed.

We will be using `class-validator` both on the front and back-end with a shared model, however when displaying errors on the front-end we'd like to have them translated via keys (using `react-i18next`). 

I think `class-validator` doesn't support `i18n` out-of-the-box, but a *monkey patch* [currently exists](https://github.com/typestack/class-validator/issues/169#issuecomment-571481577) that acts as a workaround. 

Perhaps we could hook into this and allow the user to supply their own `i18n` keys for each `ValidationType` via this monkey patch, until official support arrives? I think this will benefit a lot of users in the long run -- allowing more people to be able use this library as well 😄.

Let me know what you think!

Jeroen

**Comment by anigenero** [comment]
I want to keep away from using library-specific solutions, but allowing custom localization handling form error messages would be a really nice feature.

**Comment by anigenero** [comment]
Take a look at the PR attached to this issue. This adds a context for the library, plus options to include your own message resolution method. In your case, it would look something like this:

```typescript
const validatorOptions: ValidatorContextOptions = {
    onErrorMessage(error: ValidationError) {
        const collect = [];
        for (const key in error.contexts) {
            collect.push(
                i18next.t(error.contexts[key].i18n, {
                    target: error.target,
                    property: error.property,
                    value: error.value,
                })
            );
        }
        return collect;
    }
}

render((
    <ValidatorContext options={validatorOptions}>
        // ... rest of the app
    </ValidatorContext>
), document.getElementById('root'))
```

Which means your validation class would look something like:

```typescript
class MyValidationClass {

    @IsNotEmpty({
        context: {
            i18n: 'First name cannot be empty'
        }
    })
    public firstName: string;

}
```

Let me know if you have any questions or comments.

**Comment by jpabeem** [comment]
Damn, great work! Thanks for implementing it so quickly. That's just what I had in mind as well. I agree that the solution should not be specific to a certain library only.
